apiVersion: v1
kind: Pod
metadata:
  name: book-api-mongo-pod
  labels:
    app: book-api-mongo
spec:
  containers:
    - name: book-api-container
      image: mjabersumeria/arabbank-training:booksDemo
      ports:
        - containerPort: 3000
      env:
        - name: MONGO_URI
          value: "mongodb://localhost:27017/bookDB"
    - name: mongo-container
      image: mongo:latest
      ports:
        - containerPort: 27017
      # volumeMounts:
      #   - name: mongo-storage
      #     mountPath: /data/db

