apiVersion: v1
kind: Pod
metadata:
  name: book-api-pod
  labels:
    app: book-api
spec:
  containers:
  - name: book-api-container
    image: mjabersumeria/arabbank-training:booksDemo
    ports:
    - containerPort: 3000
  

