apiVersion: v1
kind: Service
metadata:
  name: book-api-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000  # You can specify any available port between 30000-32767
  selector:
    app: book-api
